# Generated by Django 4.0.6 on 2023-01-29 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(max_length=100)),
                ('libelle', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('prix', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanance.type')),
            ],
        ),
        migrations.CreateModel(
            name='FactureFr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('date_facturation', models.DateField()),
                ('HTaxe', models.FloatField()),
                ('Total', models.FloatField()),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanance.fournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanance.produit')),
            ],
        ),
        migrations.CreateModel(
            name='FactureCl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('date_facturation', models.DateField()),
                ('HTaxe', models.FloatField()),
                ('Total', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanance.client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanance.produit')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanance.type'),
        ),
    ]
