# Generated by Django 4.1.5 on 2023-01-26 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finanance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanance.type')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finanance.user')),
            ],
        ),
        migrations.CreateModel(
            name='Factures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(max_length=100)),
                ('libelle', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('date_facturation', models.DateField(auto_now_add=True, null=True)),
                ('prix', models.FloatField()),
                ('HTaxe', models.FloatField()),
                ('Total', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanance.client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanance.type'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finanance.user'),
        ),
    ]
