# Generated by Django 4.0.6 on 2023-01-29 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='produit',
        ),
    ]
