# Generated by Django 4.1.5 on 2023-01-26 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finanance', '0002_client_type_fournisseur_factures_client_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(max_length=100)),
                ('libelle', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('prix', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.RemoveField(
            model_name='factures',
            name='libelle',
        ),
        migrations.RemoveField(
            model_name='factures',
            name='prix',
        ),
        migrations.RemoveField(
            model_name='factures',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='user',
        ),
        migrations.AddField(
            model_name='client',
            name='FirstName',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='LastName',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factures',
            name='fournisseur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finanance.fournisseur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='FirstName',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='LastName',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factures',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanance.produit'),
        ),
    ]
