# Generated by Django 4.0.6 on 2023-01-30 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finanance', '0002_remove_produit_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PieceCompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.FloatField()),
                ('date_comptable', models.DateField()),
                ('deb', models.FloatField()),
                ('cred', models.FloatField()),
                ('Total', models.FloatField()),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanance.journal')),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanance.client')),
            ],
        ),
    ]
