# Generated by Django 4.1.5 on 2023-01-26 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanance', '0003_produit_remove_client_user_remove_factures_libelle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='FirstName',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='fournisseur',
            old_name='FirstName',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='LastName',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='LastName',
        ),
    ]
