# Generated by Django 4.0.6 on 2023-01-30 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanance', '0003_journal_piececompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piececompt',
            name='Total',
        ),
    ]
