# Generated by Django 4.0.6 on 2023-01-30 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanance', '0004_remove_piececompt_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturefr',
            name='Total',
        ),
    ]
