# Generated by Django 4.1.5 on 2023-01-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanance', '0005_rename_factures_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
