# Generated by Django 4.1.5 on 2023-01-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanance', '0006_facture_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='date_facturation',
            field=models.DateField(),
        ),
    ]
