# Generated by Django 4.0.6 on 2023-01-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanance', '0006_remove_facturecl_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturecl',
            name='journal',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturefr',
            name='journal',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
