# Generated by Django 4.1.4 on 2022-12-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0002_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking", name="days", field=models.IntegerField(),
        ),
    ]
