# Generated by Django 4.1.4 on 2022-12-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0003_alter_booking_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking", name="club", field=models.BooleanField(default=False),
        ),
    ]
